name: Web SSH Shell

on:
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y ttyd python3-pip
        pip install flask requests

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update
        sudo apt install ngrok

    - name: Run Web Shell
      env:
        WEB_USER: ${{ secrets.WEB_USER }}
        WEB_PASS: ${{ secrets.WEB_PASS }}
        FLASK_SECRET: ${{ secrets.FLASK_SECRET }}
        NGROK_AUTHTOKEN: ${{ secrets.NGROK_TOKEN }}
      run: |
        ngrok config add-authtoken $NGROK_AUTHTOKEN
        chmod +x start.sh
        ./start.sh
